CREATE DATABASE EMART;

CREATE TABLE BUYERS(
    BID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(10) NOT NULL,
    DNO VARCHAR(20) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    STATE VARCHAR(150) NOT NULL,
     PINC  VARCHAR(30),
    UID INT REFERENCES EMART_USERS(UID)

);
CREATE TABLE SELLERS(
    SID INT PRIMARY KEY AUTO_INCREMENT,
    FNM VARCHAR(150) NOT NULL,
    LNM VARCHAR(150) NOT NULL,
    EML VARCHAR(200) NOT NULL,
    MBN CHAR(10) NOT NULL,
    DNO VARCHAR(20) NOT NULL,
    STRT VARCHAR(150) NOT NULL,
    CITY VARCHAR(150) NOT NULL,
    STATE VARCHAR(150) NOT NULL,
     PINC  VARCHAR(30),
     PID INT REFERENCES PRODUCTS(PID)
);
CREATE TABLE CATEGORIES(
    CATID INT PRIMARY KEY AUTO_INCREMENT,
    CATNM VARCHAR(40) NOT NULL,
    GST NUMERIC,
);
CREATE TABLE SUBCATEGORIES(
    SUBID INT PRIMARY KEY AUTO_INCREMENT,
    SUBNM VARCHAR(150),
    CATID INT REFERENCES CATEGORIES(CATID)
);

CREATE TABLE ORDERS(
    ORDID INT PRIMARY KEY AUTO_INCREMENT,
    ORDT DATE,
    TOTALAMT NUMERIC,
    DISID INT REFERENCES DISOUNTS(DISID) 
);

CREATE TABLE PRODUCTS(
    PRID INT PRIMARY KEY AUTO_INCREMENT,
    PRNM VARCHAR(57),
    PRICE NUMERIC,
    DSCP VARCHAR(155),
    DISID INT REFERENCES DISOUNTS(DISID),
    SID INT REFERENCES SELLERS(SID)
);

CREATE TABLE ORDERDETAILS(
    ORDID INT REFERENCES ORDERS(ORDID),
    PRID INT REFERENCES PRODUCTS(PRID),
    QUANTITY INT NOT NULL,
    PRICE NUMERIC,
    TOTALAMT NUMERIC
);
CREATE TABLE TXNS(
     TXNID INT PRIMARY KEY AUTO_INCREMENT,
     AMT NUMERIC,
     TXNDT DATE,
     TTYPE INT,
     DSCP VARCHAR(250),
     BID INT REFERENCES BUYERS(BID)


 );
 CREATE TABLE DISCOUNTS(
    DISID INT PRIMARY KEY AUTO_INCREMENT,
    PRCT NUMERIC NOT NULL,
    SDT  DATE NOT NULL,
    EDT DATE NOT NULL,
    MAXC INT

);
CREATE TABLE EMART_USERS(
    UID INT PRIMARY KEY AUTO_INCREMENT,
    UNM VARCHAR(30) NOT NULL UNIQUE,
    PWD VARCHAR(25000) NOT NULL,
    ROLE VARCHAR(30) NOT NULL
);